language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t eddyong/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true eddyong/react-test npm test
after_success:
  - docker build -t eddyong/multi-client ./client
  - docker build -t eddyong/multi-nginx ./nginx
  - docker build -t eddyong/multi-server ./server
  - docker build -t eddyong/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eddyong/multi-client
  - docker push eddyong/multi-nginx
  - docker push eddyong/multi-server 
  - docker push eddyong/multi-worker
